var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                                                          y                                       ",
   "                                     yyyy                                yyy                      oy              ",
   "                                                                                                                  ",
   "                                                                                              x                   ",
   "                  y                                                                          xx                   ",
   "                 yy                                         o                               xxx                   ",
   "                                                   xx      xx                              xxxx                   ",
   "                                    o o     x xxx                                         xxxxx                   ",
   "                                                                                         xxxxxx                   ",
   "                                   xxxx                                                 xxxxxxx                   ",
   "                                       x         f       y                             xxxxxxxx                   ",
   "  xx                                      o o          yy                             xxxxxxxxx                   ",
   "  x                                                                                  xxxxxxxxxx                   ",
   "  x               f                 x     xxxxx             f                       xxxxxxxxxxx                   ",
   "  x                          xx                                                    xxxxxxxxxxxx                   ",
   "  x  @  o                             x                           xxxxx           xxxxxxxxxxxxx       oooooooo    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              x   x!!!!!!!!!!!!!!!!!!x     x                                                      ",
   "                              x!!!x!!!!!!!!!!!!!!!!!!x!!!!!x                                                      ",
   "                              x!!!x!!!!!!!!!!!!!!!!!!x!!!!!x                                                      ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                      ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                         o                                                                       ",
   "x                                        xx                                                                       ",
   "x                                        xx                                                                       ",
   "x    @                                  xxx                                                                       ",
   "xxxxxxx     f                            xx                                                                       ",
   "xxxxxxx                                  xx                                                     o                 ",
   "xxxxxxx                                 xxx                      o                       x x x                    ",
   "xxxxxxx                                  xx                      x                      x                         ",
   "xxxxxxx           x     f                xx            f   xx!!!!!!!!!xx   f           x                          ",
   "xxxxxxx          xx   x                 xxx                xx!!!!!!!!!xx              x                           ",
   "xxxxxxx   oo    xxx       xx   ooooo     xxo     oooo      xx!!!!!!!!!xx             x                            ",
   "xxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                          o  x",
   "                                                                                                         xxx x",
   "                                                                                                       x     x",
   "                                                                               x     x      x        xx      x",
   "                                                                             x                               x",
   "                                                                            x                                x",
   "                                                                           x                                 x",
   "                                                                          x                                  x",
   "                                                                         x                                   x",
   "                                                                        x          f                         x",
   "                                                                      x                         f            x",
   "                                                                    x                                        x",
   "                                                                  x                                          x",
   "                                                      x        x                                             x",
   "                                              x                                                              x",
   "                                            xx                                                               x",
   "                                          x                                                                  x",
   "  x                                      x                f                                                  x",
   "  x                                    x                                                                     x",
   "  x                                  xx                                                                      x",
   "  x                             x                                                                            x",
   "  x                           x                                                                              x",
   "  x                       x                                                                                  x",
   "  x                    x                                                                                     x",
   "  x                xx                                                                                        x",
   "  x            x                                  f                                                          x",
   "  x           x                                                                                              x",
   "  x      @   x                                                                                               x",
   "  xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  x                                                                                                          x",
   "  x                  xx     xx  xxxxx  x   x       x                x   xx   x         x       xxx           x",
   "  x                  xx     xx  x   x  x   x        x              x    xx   x x       x       xxx           x",
   "  x                   xx   xx   x   x  x   x         x            x     xx   x   x     x       xxx           x",
   "  x                     xxx     x   x  x   x          x          x      xx   x     x   x       xxx           x",
   "  x                     xxx     x   x  x   x           x   xx   x       xx   x      x  x       xxx           x",
   "  x                     xxx     x   x  x   x            x x  x x        xx   x        xx                     x",
   "  x                      x      xxxxx  xxxxx             x    x         xx   x         x       xxx           x",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x  @                                                                                                       x",
   "  xxxxxxx                                                                                                    x",
   "  xxxxxxx                                                                                                    x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
